CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
insert into productos (id, name, price) values (1, 'Cherries - Frozen', 169.03);
insert into productos (id, name, price) values (2, 'Trueblue - Blueberry Cranberry', 406.3);
insert into productos (id, name, price) values (3, 'Banana - Green', 764.03);
insert into productos (id, name, price) values (4, 'Milk - 2%', 658.41);
insert into productos (id, name, price) values (5, 'Parsley Italian - Fresh', 841.57);
insert into productos (id, name, price) values (6, 'Mix - Cocktail Strawberry Daiquiri', 640.75);
insert into productos (id, name, price) values (7, 'Soup - Campbells Beef Noodle', 82.18);
insert into productos (id, name, price) values (8, 'Langers - Mango Nectar', 69.79);
insert into productos (id, name, price) values (9, 'Eggroll', 643.19);
insert into productos (id, name, price) values (10, 'Lotus Leaves', 140.52);
insert into productos (id, name, price) values (11, 'Sauce - Soya, Dark', 293.05);
insert into productos (id, name, price) values (12, 'Pail With Metal Handle 16l White', 401.52);
insert into productos (id, name, price) values (13, 'Wine - Red, Marechal Foch', 819.65);
insert into productos (id, name, price) values (14, 'Brandy Cherry - Mcguinness', 184.24);
insert into productos (id, name, price) values (15, 'Coriander - Seed', 670.11);
insert into productos (id, name, price) values (16, 'Chicken - Ground', 956.94);
insert into productos (id, name, price) values (17, 'Rappini - Andy Boy', 545.16);
insert into productos (id, name, price) values (18, 'Sugar - Individual Portions', 480.01);
insert into productos (id, name, price) values (19, 'Ice Cream Bar - Oreo Sandwich', 226.31);
insert into productos (id, name, price) values (20, 'Flavouring - Rum', 385.28);
